envSecrets:
  MONGODB_URI: multiagent-supply-chain
  DATABASE_NAME: multiagent-supply-chain
  AWS_REGION: multiagent-supply-chain
  AWS_PROFILE: multiagent-supply-chain
  COMPLETION_MODEL: multiagent-supply-chain
  EMBEDDING_MODEL: multiagent-supply-chain
  NEXT_PUBLIC_ENV: multiagent-supply-chain

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-prod-cicd-irsa"
